name: Deploy Blog
on:
  push:
    branches:
      - main
jobs:
  build-and-deploy:
    runs-on: self-host
    steps:
      - name: Checkout code 
        uses: actions/checkout@v4
      - name: set up go
        uses: actions/setup-go@v5
        with:
          go-version: '1.25'
      - name: Build Docker Image 
        run: | 
          docker build -t myapp:latest .
          echo "building image"
      - name: Deploy to VM
        run: |
          echo "stopping existing container"
          docker stop blog || true
          docker rm blog || true
          echo "starting new container"
          docker run -d -p 8080:8080 --name blog myapp:latest
