name: Deploy Blog
on:
  push:
    branches:
      - main
jobs:
  build-and-deploy:
    runs-on: [self-hosted,mgr-sandbox]
      
    steps:
      - name: Checkout code 
        uses: actions/checkout@v4
      - name: set up go
        uses: actions/setup-go@v5
        with:
          go-version: '1.25'
      - name: Get ssh key and set perms
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.SSH_KEY }}" > ~/.ssh/id_rsa && chmod 600 ~/.ssh/id_rsa
      - name: Deploy code 
        run: scp   -o StrictHostKeyChecking=no -i ~/.ssh/id_rsa -r ./* ${{ secrets.SERVER_USER }}@${{ secrets.SERVER_IP }}:/home/${{ secrets.SERVER_USER }}/go_test/BLOG_API
      - name: Build Docker Image 
        run: | 
          export FRONTEND_PATH="${{secrets.FRONTEND_PATH}}"
          cd /home/${{secrets.SERVER_USER}}/go_test/BLOG_API
          docker build -t myapp:latest .
          echo "building image"
          
      - name: Deploy to VM
        run: |
          echo "stopping existing container"
          docker stop blog || true
          docker rm blog || true
          echo "starting new container"
          docker run -d -p 8080:8080 --name blog  --network  blog_net2 myapp:latest
